#!/bin/bash

# This pre-commit hook will keep the indexes up-to-date.
#
# To install it, from the repo root, say `cp -i tools/pre-commit .git/hooks/`.

./tools/update_indexes.js
git add "**/index.js"
